In [14]:
from pathlib import Path
import numpy as np

type = "Compression"
# type = "Tension"

direction = "X"
direction = "XZ"
direction = "Z"

file_path = r'2D_10%strain_100grains\results_grain_matpoint'
base_path = Path(r"2D_10%strain_100grains")
file_path = base_path / "results_grain_matpoint" / f"{type}{direction}"

# Project root (GNN-for-Grain-Track)
PROJECT_ROOT = Path.cwd().parent

Read strain_average

In [ ]:
index = 0
measurement = "for_ML_strain_average"
loadcase = f"{type}{direction}"

filename = (
    PROJECT_ROOT
    / "2D_10%strain_100grains"
    / "results_grain_matpoint"
    / loadcase
    / measurement
    / f"grain_{index}.txt"
)

with open(filename, "r") as f:
    lines = [line.strip() for line in f if line.strip()]

headers = lines[:10] # First 10 lines are headers

data = {}
i = 10  # start after headers

while i < len(lines):
    label = lines[i]          # e.g. increment_0
    values = lines[i+1:i+10]  # next 9 lines
    matrix = np.array(values, dtype=float).reshape(3, 3)

    data[label] = matrix
    i += 10

print(headers)
print(data["increment_0"])


['inc', 'eps_11', 'eps_12', 'eps_13', 'eps_21', 'eps_22', 'eps_23', 'eps_31', 'eps_32', 'eps_33']
[[ 1.11022302e-16 -4.50673937e-17 -1.01463696e-16]
 [-4.50673937e-17 -2.80697732e-17  6.17808888e-17]
 [-1.01463696e-16  6.17808888e-17  8.35809245e-17]]


Read strain_perMatpoint_pergrain

In [16]:
index = 0
measurement = "for_ML_strain_perMatpoint_pergrain"
loadcase = f"{type}{direction}"

filename = (
    PROJECT_ROOT
    / "2D_10%strain_100grains"
    / "results_grain_matpoint"
    / loadcase
    / measurement
    / f"grain_{index}.txt"
)

with open(filename, "r") as f:
    lines = [line.strip() for line in f if line.strip()]

headers = lines[:10] # First 10 lines are headers

data = {}
i = 10  # start after headers

while i < len(lines):
    label = lines[i]          # e.g. increment_0
    values = lines[i+1:i+10]  # next 9 lines
    matrix = np.array(values, dtype=float).reshape(3, 3)

    data[label] = matrix
    i += 10

print(headers)
print(data["increment_0"])


ValueError: could not convert string to float: '[1.11022302e-16  1.11022302e-16  1.11022302e-16  1.11022302e-16'